### ISSUE TITLE
Discussion of details for group implementation  (please add/minus or clarify stuff!!)

### ISSUE THREAD

**Issue by Theonewhomadethings** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#10]
Input: 
-User input of potential

Features:
-Command line tool 
-simulations
-Numerical solution 
-Visualisation after numerical solution

Output:
-Solution to TDSE (what form?) graphical ? numbers? text?

Processes/ mechanisms:
-Numerical solution implementation? - Crank Nicholson algorithm
-write functional/object orientated implementation of simulations showing exact, numeric and f(x)
-write functional/objectorientated of visualisation

**Comment by dascroft** [comment]
Input:

- values for functional form chosen by user

- At this current time, the user will choose 1 of 4 functional forms, then input parameters based on the chosen form. This will then yield an output below:

- Could have more functional forms but may become more tedious on UX code. May assign more members for help on this.

Output:

- Ideally in graphical form, chosen .gif but considering as mp4 available for use on a website etc

Processes/mechanisms:

- At this time, considering Numerical Solution Implementation.

**Comment by dascroft** [comment]
Already Discussed
