### ISSUE TITLE
Add test code for end user etc.

### ISSUE THREAD

**Issue by dascroft** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#17]
- examples may be to check if the program can enerate a .gif or output
- test parameters and see if the code runs correctly
- add error messages in extreme cases with high parameter sizes to conserve system resources.

**Comment by dascroft** [comment]
Perhaps modify comline code to add checks like the aforementioned above to give more information to end user? Or would that make the program less intuitive?

**Comment by Theonewhomadethings** [comment]
I will have an attempt at this.

**Comment by dascroft** [comment]
How is progress, if this issue is dead, i can close it?

**Comment by dascroft** [comment]
Issue is Stale, no further update
