### ISSUE TITLE
Divide the work load of making the input functionality for the potentials -command line, keyword arguments, inputting from a file, etc. 

### ISSUE THREAD

**Issue by AlexEJWilson** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#18]
We can discuss what each person would be best at doing, and work out the order to make different functionalities so it fits together easily.

**Comment by AlexVernis** [comment]
So who's doing what? Let's start with that

**Comment by AlexBradley0** [comment]
We already have input functionality for (I think) all potentials apart from square wells, which im working on. 
Also, now I've added some code that was missing during a merge, kwargs are now all there and good as far as I'm aware.

**Comment by dascroft** [comment]
Extended to Issue #34
