### ISSUE TITLE
Solving_tdse with functional forms.py seems to have multiple bugs

### ISSUE THREAD

**Issue by AlexBradley0** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#19]
I think it would be best to simply add a way of doing square wells to "solving_tdse.py", this would make "Solving_tdse with functional forms.py" obsolete as far as I'm aware.

**Comment by AlexVernis** [comment]
If there's a function for it, I can integrate it into tdsesolver.py, no issues.

**Comment by AlexVernis** [comment]
Actually, that should probably be moved to the src folder with the rest.

**Comment by dascroft** [comment]
In the solving tsde functional forms, func 5 contains the square wave functional form, you can use that to integrate with tdsesolver.py

**Comment by dascroft** [comment]
Tdsesolver with functional forms is just starting code and is supposed to be made obsolete

**Comment by AlexVernis** [comment]
Successfully integrated.

**Comment by dascroft** [comment]
Successfully added to comline.py, will remove function forms.py from main soon
