### ISSUE TITLE
Method of implementation for command line interface to an output

### ISSUE THREAD

**Issue by AlexEJWilson** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#20]
Run initial command line file. 

Ask user for input file path on their local computer for a text file with a potential in, or provide an arbitrary/default potential to demonstrate the program.

Once user input for potential is received (error handling/regression tests -to make sure user given function is valid) -implement solving program (solving_tdse.py), psi lists, simulations (gifs), colour plots

Outputs plot from numerical data -outputs numerical solution using fitting functions in order to get parameters

Command line --> User Input --> TDSE Solver --> Outputs
Error handling throughout

**Comment by AlexBradley0** [comment]
For user input we should probably also have a method for allowing the user to enter an equation for V(x) without having to create a file for it, this is already implemented in "solving_tdse.py". I'm not sure how one would do this through the command line but I'd imagine it's not too complicated

**Comment by AlexBradley0** [comment]
Also, I'm not sure what you meant by "Outputs plot from numerical data -outputs numerical solution using fitting functions in order to get parameters", can you explain it further?

**Comment by dascroft** [comment]
isnt the solution the output gif? where the particle in the well is being solved in time. wouldn't a numerical solution involve a fixed time which is not relevant? Unless you want a output as a function of time?

**Comment by AlexEJWilson** [comment]
In the the solving TDSE notebook https://github.com/GregoryAshton/PH3010_advanced_python/blob/main/notebooks/4_solving_schrodingers_equation_in_python.ipynb the last challenge says to output a numerical value and calculate the frequency from it. We were talking about doing this as well as the plots/gifs. I'm not sure if we'll be able to though.

**Comment by AlexBradley0** [comment]
That's just a challenge for that notebook, not something required of the project. Not saying we can't add it as an extra feature, but we should focus on getting the basics completed well first.

**Comment by dascroft** [comment]
Indeed, that is simply a Notebook challenge, the breadth of this project is open ended so we do necessarily need to follow the challenge questions. As AlexBradley0 has pointed out, we can potentially forgo this due to time constraints and work on the user input side of things.
