### ISSUE TITLE
Clean up main branch or sub-branches.

### ISSUE THREAD

**Issue by dascroft** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#22]
Once we finalise the project, cleanup obsolete code from main to avoid confusion.

**Comment by AlexBradley0** [comment]
I believe we can already remove src\\example_package\example.py and src\example_package\solving_tdse with functional forms.py

**Comment by dascroft** [comment]
Indeed, ill remove it

**Comment by dascroft** [comment]
There are two versions of tdsesolver.py, which are you willing to keep and work on?

**Comment by AlexVernis** [comment]
delete 2, it's a duplicate i made by accident

**Comment by AlexVernis** [comment]
also, are we trying to integrate tdsesolver.py into solving_tdse.py, or the other way around? asking so we know which to work on and which to copy from.

**Comment by dascroft** [comment]
Yes, if we are using classes, no if we are not

**Comment by dascroft** [comment]
Please notify me via @dascroft for any redundant code or obsolete code in the branches or main for cleanup in this issue.

**Comment by AlexBradley0** [comment]
As far as i can tell tdsesolver.py is redundant and can be removed, not certain though, @dascroft

**Comment by dascroft** [comment]
Yeah, its all integrated into solving_tdse.py so i believe it can be removed, ill preserve it in a branch in-case someone may want to reference it. It can be found on "23-adding-user-input-for-psi". Henceforth it will be removed from main until further notice.

**Comment by dascroft** [comment]
Regarding everything within the src folder that is not solving_tdse.py be removed? As they are stale

**Comment by AlexBradley0** [comment]
I believe __init__.py is necessary when it comes to creating a module, so that should probably stay. As far as i'm aware the rest can go
