### ISSUE TITLE
Adding user input for psi

### ISSUE THREAD

**Issue by AlexBradley0** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#23]
Can someone add a kwarg for user input of psi (the starting wave func).

**Comment by dascroft** [comment]
I believe this issue has already been handled and evident on main in tdse_solver.py. Are you going to continue on this or should i mark as closed since there is no branch tied to this issue?

**Comment by AlexBradley0** [comment]
I thought we weren't using tdsesolver.py anymore (should it be removed?). solving_tdse.py can't do it currently, not sure if it's getting added to it, @zhap064 was going to do it i believe

**Comment by dascroft** [comment]
Sorry, i  referred to the wrong names(they are similar) regardless kwargs have not been added to psi yet. I have created a branch for it though

**Comment by dascroft** [comment]
Any progress regarding this issue?

**Comment by AlexBradley0** [comment]
It shouldn't take too long so if @zhap064 doesn't do it I may still get round to it.
I'm not aware of any actual progress though.

**Comment by dascroft** [comment]
Yeah had a looked at the branch and no changes have been made at all, the branch is quite dead so im going to remove it and reopen it if your working on it so that you have the most up to date branch. Click 'create branch' on this issue when your ready.

**Comment by zhap064** [comment]
Are you still waiting on me or has some else already fixed it ?

**Comment by dascroft** [comment]
You welcome to work on this, but at this time no one is working on it, if this continues I will close this issue.
