### ISSUE TITLE
"solving_tdse.py" needs to be able to do square wells

### ISSUE THREAD

**Issue by AlexBradley0** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#24]
This should allow for optional user input of wall positions and a barrier with customizable height, width and position

**Comment by AlexBradley0** [comment]
This is fully implemented now, ready to merge with main.
(Unless i'm missing something i think @dascroft, you have to do this?)

**Comment by dascroft** [comment]
Merging
