### ISSUE TITLE
Adding command line compatilibity to solving_tdse.py

### ISSUE THREAD

**Issue by AlexVernis** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#25]
It's a work in progress, keep running into a series of null errors. Submitted results to new branch for examination and later adjustment.

**Comment by AlexVernis** [comment]
Realised part of this is also adding a functional kwarg to psi, so that it can be properly called and replaced by the user through cl. That's actually what was causing all the null errors. So it kinda ties into the other thread about that.

**Comment by AlexVernis** [comment]
Error has been successfully resolved, just needed a tweak in self.vx and an argument at the end changing any user-inputted "x" into "self.x_array". Command line now takes any python-formatted function directed at solving_tdse.py and outputs a graph and wavefunction to match.

Results submitted in branch "solving_tdsepy-command-line-compatibility", awaiting review.

**Comment by dascroft** [comment]
I went ahead and submitted a Pull request, however there are some conflicts with main. ill resolve them and merge to main
