### ISSUE TITLE
Can we discuss how things are going to fit together 

### ISSUE THREAD

**Issue by AlexEJWilson** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#26]
We’ve got a bunch of separate things and need to fit them together, I don’t know if you guys want to do this in person or online but we’ve got to get it sorted

**Comment by Theonewhomadethings** [comment]
Yeah we should try book a room in the library in person on wednesday maybe to finalise everything before friday deadline, but we really need to work on starting to put everything together soon before then.

**Comment by AlexBradley0** [comment]
Thats not a bad idea although I'm not sure if I'll be able to be there Wednesday. If you are doing it in person though, it's important to remember to still do as much as possible through git, cause that's what we're being marked on.

**Comment by Theonewhomadethings** [comment]
We could maybe do monday or tuesday in between lectures if that works for people instead of wednesday.

**Comment by AlexVernis** [comment]
monday/tuesday between lectures is a pretty slim timeslot, at least for me. 1-2 hours. meanwhile wednesday is free.
that said, there's nothing saying we can't do multiple days. the more work done the better, right?

**Comment by AlexVernis** [comment]
realised we never decided on a time, huh. as in something fixed.
