### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by AlexBradley0** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#28]
There should be a part of the program that checks for potentially common user errors and can raise useful errors should they occur.
One example of these may be if the user specifies xmin=10 and xmax=-10 it should raise an error saying something to the effect of "xmin is larger than xmax"

**Comment by AlexBradley0** [comment]
I think this is mostly done, and could be merged with main @dascroft . 
Although if anyone has suggestions for how to make all the try-excepts into something neater and more compact, that would be nice

**Comment by dascroft** [comment]
Regarding your branch, there is alot of conflicts regarding @TrueEnder recent commit, perhaps could you merge the code from main into version of solving_tdse.py and double check with TrueEnder once i open a new pull request since there is alot of conflicts to main.

**Comment by dascroft** [comment]
Also make sure you update your branch with main, and save your changes locally to solving_tdse.py so that your up to date with the recent commits

**Comment by AlexBradley0** [comment]
Interesting, was worried that might be the case.
I'll get on that soon.

**Comment by AlexBradley0** [comment]
*Should* be all the conflicts solved now, although some bugs may have slipped past me due to other bugs making testing hard.
Probably can merge with main now @dascroft

**Comment by dascroft** [comment]
Looking at your branch, i not quite sure its ready, it seems to be missing the argue() function and also contains alot of residual merging stuff from the pull request. Furthermore it seems a little messy. Could you perhaps have a look at it on the branch and give it a clean before i remake the pull request?

**Comment by dascroft** [comment]
Perhaps, once you do this, it may be wise to save it as solving_TDSE2.py instead since i believe @TrueEnder is still working on some potential bugs

**Comment by AlexBradley0** [comment]
Thats strange, I saved a copy just before i commited which had the argue() and stuff, something must have happened when it commited.

I'll just upload that copy as solving_tdse2.py and the incorrect version can be ignored or undone.

**Comment by dascroft** [comment]
No problem, i'm glad we caught it before it was merged

**Comment by AlexBradley0** [comment]
Should be there now, can you just confirm it looks better on your end?

**Comment by dascroft** [comment]
Yup, i had a look and it looks great, ill clean up the old code and make a pull request

**Comment by dascroft** [comment]
@AlexBradley0 Ok, so the pull request is sort of bugged, it wont quite let me merge until a conflict is resolved for a file that no longer exists. So i have an idea, make sure that the correct version of your code i.e solving_TDSE2.py is saved locally. Ill close this branch and reopen it, then go ahead and commit it again, **Give this message a thumbs up if you have it saved locally before i proceed**. Sorry about this

**Comment by dascroft** [comment]
Also, looking at the code and from @TrueEnder response to the #37, it may be safe to go ahead and merge it to main under solving_tdse.py directly with TrueEnder reviewing it

**Comment by dascroft** [comment]
@AlexBradley0 New branch name is now '28-error-messages-newbranch' and is now linked with this issue, please re-commit your code from solving_tdse2.py under the name 'solving_tdse.py' onto this branch. If you require the old branch, I can temporarily restore it to facilitate this.

**Comment by AlexBradley0** [comment]
Done that now, sorry for the delay.
@dascroft
