### ISSUE TITLE
Docstrings and comments

### ISSUE THREAD

**Issue by AlexBradley0** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#29]
Useful docstrings and comments need to be added throughout our work.

**Comment by dascroft** [comment]
I believe that this has been completed?

**Comment by AlexBradley0** [comment]
I think so. We don't need docstrings for individual functions, right? Cause they aren't being used on their own.
If we don't, yeah, it's done (might add extra comments but can close this still)
