### ISSUE TITLE
Absorb code from 4_solving_schrodingers_equation_in_python 

### ISSUE THREAD

**Issue by dascroft** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#3]
Take code from the notebook and have available for use on the project.

**Comment by dascroft** [comment]
is this Issue is completed? and ready to merge with main.

**Comment by AlexBradley0** [comment]
Yup!

**Comment by AlexBradley0** [comment]
Actually, no.
Forgot to add a way to display the video/image

**Comment by dascroft** [comment]
Ah, i see its up now, merging with main.
