### ISSUE TITLE
Command line integration causing problems for other use cases

### ISSUE THREAD

**Issue by AlexBradley0** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#31]
With the command line integration being added to the main branch the program no longer works, unless you give it --xmin, --xmax, --tmin, --tmax. 
Not only does this make things more difficult for the end user, as they should not have to specify anything they don't want to, but it will also likely cause issues when using the program as a module.

Is there any way to solve this? 
Would it be possible to have the command line section as a separate file that calls solving_tdse.py as a module, or something similar?

**Comment by AlexVernis** [comment]
i think the easy solution to that would just be switch some "True"s to "False"s in the args block. Just to make them not required. If that's done then everything should run fine without them.

**Comment by AlexBradley0** [comment]
Doing that causes some other issue:
line 169, in argue
    args.vx = args.vx.replace("x","self.x_array")

AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by AlexVernis** [comment]
oh, that's to do with entering the equation. Forgot that that could cause an issue if nothing is inputted.
If the replace is put into an "if" statement that checks if there was actually anything input for vx, that should resolve that. I can handle that later, I think. 

Regardless, having no parameters might actually cause problems (it has before). I have some ideas in the works, but nothing concrete yet. I'll run some checks on those.

**Comment by AlexVernis** [comment]
> Doing that causes some other issue: line 169, in argue args.vx = args.vx.replace("x","self.x_array")
> 
> AttributeError: 'NoneType' object has no attribute 'replace'

I've done some testing, and this actually goes for every single input. Presumably, it's something about the way the kwargs are written that's not quite compatible with the commandline. I'll try adding some int() and str() in to see if that resolves anything.

**Comment by AlexVernis** [comment]
Hm, no, it seems the issue is actually that having no input makes the floats just stop working (no input --> null value). Presumably there's a way to make this work, it could just take a bit.

**Comment by AlexVernis** [comment]
Hm. Removing the float() from the variables makes those errors stop appearing, but now it's causing issues with x_array.

`File "C:\Users\USER\Solving-TDSE-for-an-Arbitrary-V-x-\src\Python_code\solving_tdse.py", line 181, in <module>`
   `TDSE = TDSE(vx = args.vx, xmin = args.xmin,xmax = args.xmax,tmin = args.tmin,tmax=args.tmax,k = args.k, p = args.p, output = args.output)`
`File "C:\Users\USER\Solving-TDSE-for-an-Arbitrary-V-x-\src\Python_code\solving_tdse.py", line 30, in __init__`
   `self.x_array = np.linspace(self.xmin, self.xmax, self.Nx)`
`File "<__array_function__ internals>", line 5, in linspace`
`File "C:\Users\USER\anaconda3\lib\site-packages\numpy\core\function_base.py", line 127, in linspace`
   `start = asanyarray(start) * 1.0`
`TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'`

**Comment by AlexBradley0** [comment]
The floats shouldnt ever end up with nothing to "float", because kwargs.get gives a default value it uses if the user doesnt specify anything?
Not sure, perhaps I'm misunderstanding what the problem is

**Comment by AlexVernis** [comment]
Yeah, I don't get it either. Because that's exactly the problem: adding nothing for some reason just makes the value a nothing. Even if it's not called.

**Comment by dascroft** [comment]
start = asanyarray(start) * 1.0, the operation here is a Nonetype multiplied by float?, perhaps you need to set the asanyarray as a float? or would that not work?

**Comment by AlexVernis** [comment]
asanyarray is a part of numpy, i can't really edit that. So no, I don't think that would work.

**Comment by dascroft** [comment]
Ah this is an error within numpy function? Ah then yes your right, this wouldnt work

**Comment by AlexVernis** [comment]
this was caused by removing the float() around the xmin, xmax, etc. kwargs. Leaving them in still causes NoneTypes, just up there instead. Something about leaving them blank is causing the kwarg to turn into nothing rather than taking the default. Maybe this could be solved by a series of if statements, but that'd be pretty clunky.

That said, it's the best idea I've had yet. Gonna try that out.

**Comment by dascroft** [comment]
Btw what branch are you working on?

**Comment by AlexVernis** [comment]
Honestly: I forgot to start a new branch for it, I just pulled to local. I'll probably make a new one when I get closer to completion, then just save my local changes and move over there. It's kind of a mess, but eh.

**Comment by dascroft** [comment]
Ah, ill make a branch within this issue, makes it easier when it comes to pull requests. Once your done locally, go ahead and port it on that branch

**Comment by AlexVernis** [comment]
The issue has been seemingly resolved. It's messy, and full of if statements, but the command line now runs with no errors even with no parameters added. Await push to branch, coming soon.

**Comment by dascroft** [comment]
Let me know once you have pushed to branch, we will review it and add to main.

**Comment by AlexVernis** [comment]
i uh. accidentally just commited to main. please revert.

**Comment by dascroft** [comment]
I dont see a pull request?,  did you do it via the command line or anaconda? If so maybe git undo merge or "git reset --soft HEAD~1" where HEAD (the last commit) to one commit before in the log history. Use "git log --oneline" to see log of commits. The pull request feature makes this process easier and more trackable so in future its best to make sure your on the right branch before you commit anything and utilise pull requests when merging to main

**Comment by AlexVernis** [comment]
Crisis resolved. Changes have now been pushed to the _correct_ branch. Awaiting pull.

**Comment by dascroft** [comment]
Great! I'll open a pull request
