### ISSUE TITLE
What is left to do and who is doing it?

### ISSUE THREAD

**Issue by AlexBradley0** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#34]
Here is everything I can think of:
Command line input (in progress, worked on by @TrueEnder )
Documentation (I'm about to start work on this, help is welcome)
Docstrings (I plan to work on this, help is welcome although as I wrote most of the code it may be most efficient if I do most of it)
Test code (@Theonewhomadethings said they would have a go, any update on this?)
General testing
Making the code work as a module that people can install (not sure how to do this)

Extra features? (Everyone is welcome to suggest/add something, bear in mind we need the basics working first and foremost)

Does anyone have anything else to add, or want to claim something to work on (jointly?)

**Comment by dascroft** [comment]
README.MD needs to be updated, however this is a little troublesome since we dont have a workable command-line user interface yet

**Comment by AlexBradley0** [comment]
I was going to make a start on this (was classing it under documentation)
Can give info on the kwargs and stuff at least

**Comment by AlexVernis** [comment]
Command line input is now messy, but functional. Generally runs without errors, at least from what I've checked.

**Comment by AlexBradley0** [comment]
> Command line input is now messy, but functional. Generally runs without errors, at least from what I've checked.

Now that you've done this, could you do some documentation for it?   (stuff like comments, update README, maybe docstrings)

**Comment by AlexVernis** [comment]
I presume that means add usage instructions to the readme? Can do, and the rest too.

**Comment by dascroft** [comment]
Yeah, pretty much just add a subtitle describing how to use the program

**Comment by dascroft** [comment]
I added a instructions title in the Readme, you can give some brief instructions, and submit them on the main branch, I can review it and make some changes if need be.

**Comment by AlexVernis** [comment]
By "submit on the main branch" I presume you just mean edit the readme right here? And in that, just instructions on how to run solving_tdse and properly input values? or is there more

**Comment by AlexBradley0** [comment]
The Readme also needs to have instructions on installing the whole thing, and using it as a module (which we havnt quite done yet)

**Comment by dascroft** [comment]
It has some basic instructions regarding installation, as for the using it as a module part perhaps we should not work on that and focus on finalising the project? Check the program is working correctly and the documentation is completed.

**Comment by AlexBradley0** [comment]
If i remember right it was one of the main features that was wanted from this project, so we should try and do it if theres time

**Comment by dascroft** [comment]
I opened an issue for it incase someone would like to work on it, feel free to open a branch for that.

**Comment by zhap064** [comment]
Does anyone know if git only works on the lab computers or can we work in the library ?

**Comment by AlexVernis** [comment]
presumably it should work fine. but i'm not certain on that.

**Comment by zhap064** [comment]
I've opened the prompt and it says it doesn't recognise git so should i just install it.

**Comment by AlexBradley0** [comment]
Oh, I'd have said unlikely. Pretty sure the lab computers are set up with specific stuff for physics and I'd imagine git is one of those things.
Alternatively you could use github specifically, and manually pull, commit etc through github

**Comment by AlexBradley0** [comment]
Ah, suspected so, it may not let you install it, permissions n all that

**Comment by AlexVernis** [comment]
maybe the desktop app? though that might not help much.

**Comment by dascroft** [comment]
For lab computers some work with git when opening Anaconda Prompt, but if your at home on a personal computer your going to need to install Anaconda, pip and git if your doing this from scratch. Another method is just simply having spyder, copy pasting code from a branch, working on it, then through github.dev pasting in and commiting to your branch. Library ones, I'm not sure.

**Comment by zhap064** [comment]
I think I've managed to get it to install
