### ISSUE TITLE
Convert code to be used as a module.

### ISSUE THREAD

**Issue by dascroft** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#42]
If there is time, we can work on converting the code as a package that can be run.

**Comment by AlexBradley0** [comment]
I've looked into this and should be reasonable easy, but it should probably be the last thing we do. It shouldnt need any modifications to the existing code, just needs to be packaged and uploaded (possibly some instructions writing too).
With the extension till Tuesday I'll do it Monday afternoon/evening perhaps?   So everything will need to be finalized before then.

**Comment by dascroft** [comment]
About the extension, i believe his email says that we should work on finalising what already there, than new features and that if we want to do anything new, we need to email him or something?

**Comment by AlexBradley0** [comment]
I'd have classed this as an "outstanding part of the group project", which sounded like was fine?
Perhaps I'm misinterpreting what he said, it wouldn't hurt if you sent him an email to check

**Comment by dascroft** [comment]
Alright, ill send him an email.

**Comment by Theonewhomadethings** [comment]
Could I package the software? as I feel like I haven't been able to contribute as much as I wanted.

**Comment by dascroft** [comment]
Of course, ill make a branch for this issue, and you can use that space to work on it.

**Comment by Theonewhomadethings** [comment]
Cool. so when should I do it for? the Friday old deadline or for the Tuesday new deadline. As It wont take long

**Comment by dascroft** [comment]
Whenever you can, between now and Tuesday is fine, though I sent Gregory an email for this issue and i'm awaiting a response.

**Comment by Theonewhomadethings** [comment]
K

**Comment by Theonewhomadethings** [comment]
in case anyone's wondering, to confirm I am completing this now

**Comment by Theonewhomadethings** [comment]
https://packaging.python.org/en/latest/tutorials/packaging-projects/#creating-the-package-files
Hi guys, was wondering if anyone sees this tonight. For this issue would you like me to do what the link above suggests and:
Generate distribution archives and upload the distribution archives to the python package index for the python project we have made? like what sort of output are you expecting from this step.

**Comment by Theonewhomadethings** [comment]
its literally a couple of lines just need clarification on what the output we as a group are expecting

**Comment by Theonewhomadethings** [comment]
![image](https://user-images.githubusercontent.com/88815725/203150424-08015343-ea01-41c7-845e-830cb3949912.png)

**Comment by Theonewhomadethings** [comment]
trying to install the package and running into errors. The code py -m build is supposed to output a .whl and .gz file

**Comment by Theonewhomadethings** [comment]
nvm i fixed the error in pyproject.toml file 
![image](https://user-images.githubusercontent.com/88815725/203155012-cb10494f-729a-4554-9913-56a94da43510.png)

**Comment by Theonewhomadethings** [comment]
https://test.pypi.org/project/Solving-tdse-group-c/0.0.1/
^^ is the link for the package on test pypi which is a separate instance of the package index intended for testing and experimentation.

**Comment by Theonewhomadethings** [comment]
to test if it works we run the line:
py -m pip install --index-url https://test.pypi.org/simple/ --no-deps Solving_tdse_group_c

apparently

**Comment by Theonewhomadethings** [comment]
we need to merge my branch with main btw as the .toml file has 1 wrong syntax in the name

**Comment by dascroft** [comment]
I had a look at your branch and you only modified the .toml file so i pushed it as instructed.
