### ISSUE TITLE
Command line section causing every warning to trigger

### ISSUE THREAD

**Issue by AlexBradley0** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#43]
UserWarning: None is not valid as xmin, using default of -5    (and similar warnings for other parameters)

This is due to the command line giving values of 'none' if not value is specified. Is there any way to make it give correct defaults?
Another potential solution that i think would be better in theory, but more work, is to split the command line section into a different file, that can call solving_tdse as a module and give it inputs through kwargs.

**Comment by AlexBradley0** [comment]
I may have a quick look into my second proposed solution soon, gonna create a branch for it but if it doesn't work and i give up, or I never get round to it I'll delete it again

**Comment by dascroft** [comment]
Isn't the program working as intended, you didn't specify a parameter so it defaulted to -5 for the case of xmin? I.e the correct default? I'm not sure what you mean.

**Comment by AlexVernis** [comment]
that should already be resolved, i put in some if statements that got rid of unintended NoneTypes (or at least they're meant to). i'll run some checks of my own in a bit to see if that's become an issue again somehow. (though it shouldn't have)

**Comment by AlexBradley0** [comment]
Ah I think i see the issue, the section that runs the checks got put before your fix

**Comment by AlexBradley0** [comment]
Oh, but switching the order causes "'TDSE' object has no attribute 'xmin'"
I cant see an easy way of keeping the warnings working for invalid inputs, but not having them triggered by empty ones from the command line

**Comment by AlexVernis** [comment]
maybe you could splice them together? as in, have the warning show up as part of my NoneType check

**Comment by dascroft** [comment]
If the warnings are functioning correctly anyway due to none parameters, then I think its okay to keep them as is or do what TrueEnder suggested.

**Comment by AlexBradley0** [comment]
I think the warnings shouldnt trigger if the user just doesnt input a value, because otherwise that'll be extremely annoying for the user. If they just wanted to run the default setup, it would trigger every warning, or they have to go and manually enter everything

**Comment by dascroft** [comment]
I see, then could you consider writing to a warnings.txt? Or log.txt for them? Maybe less user-intuitive but still informative nonetheless.

**Comment by AlexBradley0** [comment]
Okay, come up with a solution:
![image](https://user-images.githubusercontent.com/116880130/202223544-eeaae5da-4fbe-4922-b314-29da4cc861c0.png)
moving the float to the end now means the try cant fail until its checked for 'none'
It's gonna be awful to look at, but it'll work

**Comment by AlexVernis** [comment]
how about a check for if the value isn't a valid integer/float? that way if it gets past the "not None" (which would set all required none to integer) then it'll criticise them for putting something that isn't valid

**Comment by AlexBradley0** [comment]
Thats basically what the try --> float does, checks for if its a number by whether or not it can float() it without crashing. Cause when it takes in a kwarg it does so as a string, not an int or float,

**Comment by dascroft** [comment]
I made a branch for it, you can work on it there

**Comment by AlexBradley0** [comment]
Cool, will do
Shouldnt take long

**Comment by AlexBradley0** [comment]
Done!
Hopefully it will commit and merge properly this time           @dascroft

**Comment by AlexBradley0** [comment]
I may still experiment with splitting the main section and the command line into separate files, i imagine it making use as a module or a python file on its own easier. But i'm aware we're short on time so now this is solved I won't prioritize it.
