### ISSUE TITLE
run error - TDSE.plot() not working

### ISSUE THREAD

**Issue by AlexVernis** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#45]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/116894937/202238065-6583061d-481c-4879-8421-aa9ee44e7215.png">
I think one of these shouldn't be in there.

**Comment by AlexVernis** [comment]
For context, I tried to get a plot through commandline, but it seems this line of code in particular isn't working right.

**Comment by AlexVernis** [comment]
Animation works fine, by the way - it's only plot that's causing issues.

**Comment by AlexVernis** [comment]
<img width="462" alt="image" src="https://user-images.githubusercontent.com/116894937/202243062-0912fec8-bc8f-46cc-aa85-0c94d11883d6.png">
switching to just "self" in there instead raises errors in the "checks" block, so it seems that might be part of the cause.

**Comment by AlexVernis** [comment]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/116894937/202244070-2d81c877-d6ae-4c88-9edb-6b0d3e731e5d.png">
I feel like this might also be the cause of some issues. It also feels redundant, because it's already done at the end. Maybe the warning function could be integrated into that part, though.

**Comment by AlexVernis** [comment]
@AlexBradley0 Was `psi_mag_squared` always called with two variables like that, if so do you have any input on what might be broken here? And if not, when did this change happen? My current thinking is that this was done after the integration of TDSE.checks, and that something about it is causing things to break, because this did not happen before.

**Comment by AlexVernis** [comment]
Found a solution. Within the function, it has to be `self.checks()` instead of `TDSE.checks(self)`. Same with `psi_mag_squared`.

**Comment by dascroft** [comment]
Great! Commit your fix to the branch associated with this issue.

**Comment by dascroft** [comment]
Feel free to open a pull request and merge once you have implemented it, make sure to review it before you merge and resolve any conflicts.
