### ISSUE TITLE
Splitting command line section into seperate file

### ISSUE THREAD

**Issue by AlexBradley0** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#48]
This should make creating a module smoother, and may help solve some minor lingering issues

**Comment by AlexBradley0** [comment]
This has been done and tested.
Assuming we're all okay with this change it can be merged with main @dascroft   (could be a messy merge, @ me if there are issues)

**Comment by dascroft** [comment]
I opened a pull request, I have added @TrueEnder as a reviewer also, before we merge to main

**Comment by AlexBradley0** [comment]
Cool
Yeah, I'd recommend testing it yourselves!

**Comment by dascroft** [comment]
Great! I think there is 2 duplicate python files, tdse_cmd.py, and untitled0.py. I'm guessing you want to keep tdse_cmd.py. I reviewed it myself, seems to be working correctly.

**Comment by AlexVernis** [comment]
One question: how is this run now? As in, which program should be called from cl to run? Because if it's any different then README.md might need to be updated again.

**Comment by dascroft** [comment]
It's aleady been updated by @AlexBradley0, in the recent commit for ReadMe.md. The instructions now say to use tdse_cmd.py

**Comment by AlexVernis** [comment]
Ah, good.

**Comment by AlexBradley0** [comment]
Yes about the duplicates, it is the tdse_cmd that is to be kept, tried to update the name but apparently it just duplicated it.

And yes, from the command line just do the same as you used to but with tdse_cmd.py instead of solving_tdse.py

**Comment by AlexVernis** [comment]
I just tried, and it's not working for me. #50
