### ISSUE TITLE
Program split causing None errors

### ISSUE THREAD

**Issue by AlexVernis** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#50]
Splitting the programs seems to have caused more NoneTypes to start springing up when using the command line. Presumably, the issue is that it's been split from the required checks.
![image](https://user-images.githubusercontent.com/116894937/202555741-5207fc1b-520e-41d1-a429-fd897aeec59a.png)

**Comment by AlexBradley0** [comment]
Ooh interesting, wasn't getting that my end.
Is this after it was merged with main, or before?

**Comment by AlexVernis** [comment]
I just pulled from main for testing, so presumably after.

**Comment by AlexBradley0** [comment]
Yes, i'm getting them now too (from main), will sort that!

**Comment by AlexVernis** [comment]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/116894937/202558306-077a69a4-2776-455b-bbab-32dd33a1c450.png">
swapped line order, this way seems to fix it

**Comment by dascroft** [comment]
Nice!, just commit directly to main if it solves the issue
