### ISSUE TITLE
Redundant file?  comline-loader.ipynb

### ISSUE THREAD

**Issue by AlexBradley0** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#51]
in the main folder (with README etc), it looks very outdated and hasnt been updated in almost a week, pretty sure its not needed anymore.

**Comment by dascroft** [comment]
Actually, its good for future reference, ill move it to a directory called old_python_code.

**Comment by AlexVernis** [comment]
Good call, yeah. comline_loader is the file I made that generated the old `tdse_solver.py`, it can be put into storage now.
