### ISSUE TITLE
Potential Bug: AttributeError: 'PolyCollection' object has no property 'shading'

### ISSUE THREAD

**Issue by dascroft** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#53]
![Capture](https://user-images.githubusercontent.com/116877781/202562681-89afe1ec-f4ca-4cd9-9b8a-aa41d4841ccd.PNG)

**Comment by dascroft** [comment]
I generated a 2*x**2 vx with output plot and it threw an attribute error, any ideas?

**Comment by AlexVernis** [comment]
Honestly? No idea. Seems like something's broken down within your copy of matplotlib, because running it myself has led to no such error. Try running it again?

**Comment by dascroft** [comment]
Well, seems like i needed to run pip install --upgrade matplotlib and now it works. *facepalm

**Comment by AlexBradley0** [comment]
Seems fine for me
![image](https://user-images.githubusercontent.com/116880130/202563698-55f91e0d-9b89-488a-ab0b-1d2698c68250.png)

I'd agree it may be an issue on your end
