### ISSUE TITLE
Anything else important to do?

### ISSUE THREAD

**Issue by AlexBradley0** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#54]
Aside from creating a module, I believe that we have everything important done (without starting anything major, e.g. code for proper testing).

**Comment by AlexBradley0** [comment]
If the answer is no, then the main thing to do would be a final pass for bugs, readability, comments, user friendliness etc.

I'm also gonna add a small section which allows the option of outputting as a csv for use in a different plotting program.

**Comment by dascroft** [comment]
I cc'd you in the email so you can have a read of what i sent

**Comment by AlexBradley0** [comment]
If someone has a bit of time before the deadline, perhaps add a small section that displays the output automatically.
Or maybe change the location it saves to, to somewhere more useful e.g. pictures

**Comment by Theonewhomadethings** [comment]
i think he changed the deadline for tuesday so I can do some of these small things now

**Comment by AlexVernis** [comment]
while you do, be sure to run checks every so often, just to make sure you haven't accidentally broken anything (it happens to everyone).

**Comment by dascroft** [comment]
I believe that there is no longer anymore work to be done, I think its safe to assume that this project has finished. Thanks to everyone who contributed!
