### ISSUE TITLE
testing for code?

### ISSUE THREAD

**Issue by Theonewhomadethings** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#56]
Which programs shall I add some basic testing too or do some error handling for. I had done some research last week but wasn't sure which programs needed it applied to specifically.

**Comment by AlexBradley0** [comment]
I think error handling is completed.
The code for testing should be made for solving_tdse.py, not sure if tdse_cmd.py needs it.

**Comment by dascroft** [comment]
Indeed, its all handled by warnings now, should i close this issue? Unless you mean tests through flake8? then not at the moment but im not sure its even needed at this point

**Comment by Theonewhomadethings** [comment]
damn I had code planned for that. close the issue i guess
