### ISSUE TITLE
Modify TDSE code from notebook_4 to allow for user input.

### ISSUE THREAD

**Issue by dascroft** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#6]
Modify code to allow for user input

- Allow user to Set values of k parameter (coefficient)
- Allow user to set values for x power.

**Comment by AlexBradley0** [comment]
Would it be better to split this issue into separate issues? One for each of:
1) User input of constants (mainly k)
2) The form of V(x), including the power of x
3) The form of psi(x), believe this is the wave function? (not sure if this one is necessary)

**Comment by dascroft** [comment]
So your suggesting a different functional form entirely for v(x)? we would maybe have to have the user choose functional forms and then let them define the parameters if that's the case

**Comment by AlexVernis** [comment]
i believe too much user input would end up getting very messy, very quickly.
best to limit it to just a few variables, i think.

**Comment by AlexBradley0** [comment]
I dont think it would get messy for the user if we used kwargs. Then if the user doesnt want to use them, they dont have to

**Comment by dascroft** [comment]
Expanded on another issue, dead hence marked as closed
