### ISSUE TITLE
Create user input environment via command line interface. 

### ISSUE THREAD

**Issue by dascroft** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#7]
Users should be able to input parameters and get a .gif as an output based on their parameters.

**Comment by AlexVernis** [comment]
Progress is being made on the variety of functional forms, also inputting boundary parameters shouldn't pose much further issue. We are limited in the number of variables we can use, though.

**Comment by dascroft** [comment]
Adding more functional forms is fine, as for boundary conditions, wouldn't you need to define new variables, or could you have the user specify a range of x values acceptable?

**Comment by AlexVernis** [comment]
it's not really defining new variables as it is allowing the user to call existing ones. in theory just having the range selectable by the user as "xmin" and "xmax" would work well enough.

**Comment by AlexVernis** [comment]
i've figured out the issue. i think it's not in the code, it's in the html printing of the image, because i checked the file on a whim and what do you know, perfect result.

**Comment by AlexVernis** [comment]
New code has now been merged in. Awaiting review.

**Comment by dascroft** [comment]
I merged to main, nice output though its in Jupyter notebook format. we can always change it though
