### ISSUE TITLE
Users choose 1 of 4 functional forms for V. Have input parameters.

### ISSUE THREAD

**Issue by dascroft** [dascroft/Solving-TDSE-for-an-Arbitrary-V-x-#9]
Simple functions:

- linear/user inputted power

- exponential

- sin and cos

**Comment by AlexEJWilson** [comment]
Could we make the user choose either:

polynomial - ax^1 +cx^2 + fx^3 +etc and make them chose what order polynomial


non-linear - ab^x

or maybe ask for specific boundaries like x<a : V(x) = b like for the infinite square well

**Comment by dascroft** [comment]
Yeah, you can ask the user to define boundary conditions. The functional forms list is WIP, and adding more functional forms will only enhance the program. We'll move this to the next issue.
